### ISSUE TITLE
1.20.x support?

### ISSUE THREAD

**Issue by RealmKebab** [ArcanePlugins/BetterCommandSpy#12]
When is 1.20.x support gonna come out

**Comment by lokka30** [comment]
Hey, it should work out of the box with 1.20 support :)
Before I officially state 1.20 support I want to make some code refreshments and verify there are no limitations

**Comment by RealmKebab** [comment]
> Hey, it should work out of the box with 1.20 support :) Before I officially state 1.20 support I want to make some code refreshments and verify there are no limitations

Okay
